WARNING:tornado.access:404 GET /favicon.ico (::1) 2.27ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.48ms
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.82ms
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.49ms
ERROR:tornado.application:Uncaught exception GET /simulations/2021062418013441/broadcast (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/simulations/2021062418013441/broadcast', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 278, in get
    await self.ws_connection.accept_connection(self)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 879, in accept_connection
    await self._accept_connection(handler)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 962, in _accept_connection
    await self._receive_frame_loop()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 1119, in _receive_frame_loop
    self.handler.on_ws_connection_close(self.close_code, self.close_reason)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 576, in on_ws_connection_close
    self.on_connection_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 568, in on_connection_close
    self.on_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/envision/server.py", line 262, in on_close
    del WEB_CLIENT_RUN_LOOPS[self._simulation_id]
KeyError: '2021062418013441'
ERROR:tornado.application:Uncaught exception GET /simulations/2021062418013449/broadcast (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/simulations/2021062418013449/broadcast', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 278, in get
    await self.ws_connection.accept_connection(self)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 879, in accept_connection
    await self._accept_connection(handler)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 962, in _accept_connection
    await self._receive_frame_loop()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 1119, in _receive_frame_loop
    self.handler.on_ws_connection_close(self.close_code, self.close_reason)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 576, in on_ws_connection_close
    self.on_connection_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 568, in on_connection_close
    self.on_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/envision/server.py", line 262, in on_close
    del WEB_CLIENT_RUN_LOOPS[self._simulation_id]
KeyError: '2021062418013449'
ERROR:tornado.application:Uncaught exception GET /simulations/2021062418013441/broadcast (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/simulations/2021062418013441/broadcast', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 278, in get
    await self.ws_connection.accept_connection(self)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 879, in accept_connection
    await self._accept_connection(handler)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 962, in _accept_connection
    await self._receive_frame_loop()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 1119, in _receive_frame_loop
    self.handler.on_ws_connection_close(self.close_code, self.close_reason)
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 576, in on_ws_connection_close
    self.on_connection_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/tornado/websocket.py", line 568, in on_connection_close
    self.on_close()
  File "/home/dikshant/github/SMARTS-lite/ultra/.VENV/lib/python3.7/site-packages/envision/server.py", line 262, in on_close
    del WEB_CLIENT_RUN_LOOPS[self._simulation_id]
KeyError: '2021062418013441'
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.75ms
WARNING:tornado.access:404 GET /favicon.ico (::1) 4.55ms
WARNING:tornado.access:404 GET /favicon.ico (::1) 2.03ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.52ms
